# A lie, but that shouldn't matter.
language: c

services:
  - docker

sudo: required

# We override what to do anyway.
script: sudo ./test.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always
