# Run MediaWiki, RESTBase & Parsoid using `docker-compose up`


mediawiki:
  image: benhutchins/mediawiki
  ports:
    - "80:80"
  links:
    - mysql
    - node-services
  volumes:
    - /var/lib/mediawiki-docker-compose/mediawiki-core:/data:rw
  environment:
    - MEDIAWIKI_SITE_SERVER=//localhost
    - MEDIAWIKI_SITE_NAME=MediaWiki
    - MEDIAWIKI_SITE_LANG=en
    - MEDIAWIKI_ADMIN_USER=admin
    - MEDIAWIKI_ADMIN_PASS=rosebud
    - MEDIAWIKI_UPDATE=true
    # TODO: Replace sleep with DB socket polling in container. Something like this:
    # while [ `nc $MEDIAWIKI_DB_HOST $MEDIAWIKI_DB_PORT < /dev/null; echo $?` != 0 ] ; do
    #   echo 'waiting for mysql...' ;
    #   sleep 1 ;
    # done
    - MEDIAWIKI_SLEEP=15
    - MEDIAWIKI_VERSION=1.25.2
    - MEDIAWIKI_DB_USER=root
    - MEDIAWIKI_DB_HOST=mysql

mysql:
  image: mysql
  volumes:
    - /var/lib/mediawiki-docker-compose/mediawiki-mysql:/var/lib/mysql:rw
  environment:
    - MYSQL_ROOT_PASSWORD=password

node-services:
  image: wikimedia/mediawiki-node-services
  # Temporarily expose RB port directly.
  # TODO: Set up rewrite at /api/rest_v1/.
  ports:
    - "7231:7231"
  volumes:
    - /var/lib/mediawiki-docker-compose/node-services:/data
